### ISSUE TITLE
gestion export

### ISSUE THREAD

**Issue by mruiz-sa** [mruiz-sa/Minishell#10]

**Comment by manu-garcia** [comment]
In src/env.c there is a function we can use:

int	set_env(char ***envp, char *key, char *value)

It will modify the var if exist, or add it if it does not.

**Comment by manu-garcia** [comment]
declare -x manu
declare -x mikel="1"

Poner "declare -x" delante de las variables
Export muestra todas las variables. env, sin embargo no muestra las variables sin valor
