### ISSUE TITLE
gestionar ctrl-C ctrl-D ctrl-\

### ISSUE THREAD

**Issue by mruiz-sa** [mruiz-sa/Minishell#18]

**Comment by mruiz-sa** [comment]
Esto cierra comandos bloqueantes como el cat!!

**Comment by manu-garcia** [comment]
![Screenshot 2022-09-24 at 17 21 18](https://user-images.githubusercontent.com/24234153/192105962-d7e24c20-6aad-45c2-94a4-e917a5c7b3bf.png)

**Comment by mruiz-sa** [comment]
Quitar ^C

**Comment by manu-garcia** [comment]
Parece que se puede hacer con funciones permitidas en el subject que todavia no usamos. El termino es "termius"

**Comment by manu-garcia** [comment]
Hay problemas con comandos bloqueantes

minishell: cat
hola
CTRL-C o \
